version: '3.8'

services:
  mongodb:
    image: mongo:7.0 
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db 
      - ./dados:/dados
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    restart: unless-stopped
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
    mongo-network:
        driver: bridge
volumes:
    mongo_data: 
        driver: local
